### ISSUE TITLE
android.content.Context Cannot be Resolved

### ISSUE THREAD

**Issue by DavidB-TPW** [ketai/ketai#11]
I am trying to use Ketai to interact with a SQLite database, but I cannot because I keep getting two errors in the console:

`The type android.content.Context cannot be resolved. It is indirectly referenced from required .class files	The type android.content.Context cannot be resolved. It is indirectly referenced from required .class files`

`The method load(Context, String, String) from the type KetaiSQLite refers to the missing type Context	The method load(Context, String, String) from the type KetaiSQLite refers to the missing type Context`

Processing Version: `3.0 beta 5`
Processing Android Mode Version: `0242`

![Ketai SQLite Processing Issue](https://cloud.githubusercontent.com/assets/13968410/9475516/2a0b5b62-4b35-11e5-809b-2e310d7133e0.png)

**Comment by ketai** [comment]
fixed, based off of the PApplet moving to a Fragment vs. Activity previously

**Comment by DavidB-TPW** [comment]
I apologize, as I was not aware that a duplicate of this existed.
