### ISSUE TITLE
Is bluetooth 4.0 supported with the Ketai app?

### ISSUE THREAD

**Issue by viggi1000** [ketai/ketai#14]
Guys will bluetooth 4.0 UART nrf51 work with the Ketai library?

**Comment by wolfm2** [comment]
It looks like someone had had success with ketai an Adafruit breakout board featuring the same Nordic BLE chip:  https://forum.processing.org/two/discussion/14247/i-need-someone-knowledgeable-on-bluetooth-low-energy-and-android-mode

Best,
Michael
