### ISSUE TITLE
surfaceTouchEvent error?

### ISSUE THREAD

**Issue by hudsonm4000** [ketai/ketai#15]
Just installed Processing 3.0b6 and my code is throwing a new error that didn't exist before:

For the code below, copied direct from Rapid Android Development, Processing is telling me that
the function "surfaceTouchEvent(MotionEvent)" does not exist. 

Is this a Processing bug or a Ketai issue with 3.0b6?

public boolean surfaceTouchEvent(MotionEvent event) {
  if (setUpComplete) {
    //call to keep mouseX, mouseY, etc updated
    super.surfaceTouchEvent(event);
    //forward event to class for processing
    return gesture.surfaceTouchEvent(event);
  } else {
    return false;
  }
}

Hope you can help?

Mark

**Comment by ketai** [comment]
Please update your android mode to the latest.  There was an issue with the last version of the android mode.
