### ISSUE TITLE
Compiling error Ketai

### ISSUE THREAD

**Issue by imartini** [ketai/ketai#19]
Hi!

I'm trying to compile Ketai from eclipse, but can not. I get a warning on the compilation ant:

[javac] Compiling 27 source files to C:\Users\Rider\workspace\test\ketai-master\bin
    [javac] C:\Users\Rider\workspace\test\ketai-master\src\ketai\camera\KetaiCamera.java:15: error: package javax.microedition.khronos.opengles does not exist
    [javac] import javax.microedition.khronos.opengles.GL10;
    [javac]                                           ^
    [javac] C:\Users\Rider\workspace\test\ketai-master\src\ketai\camera\KetaiCamera.java:19: error: package android.content.pm does not exist
    [javac] import android.content.pm.ApplicationInfo;
    [javac]                          ^
    [javac] C:\Users\Rider\workspace\test\ketai-master\src\ketai\camera\KetaiCamera.java:20: error: package android.content.pm does not exist
    [javac] import android.content.pm.PackageManager;
.
.
.

And 73 more errors. I need import some Android jar library? 

Thanks

**Comment by IngenieroElectronico** [comment]
Look in this channel good information of APDE, Ketai and Arduino:

https://www.youtube.com/channel/UCyWRJgfJMu3fiW4xO0FmB1w/videos?sort=dd&shelf_id=0&view=0

**Comment by ketai** [comment]
Make sure that there is a version of the ADK is associated with the project.  

Select the project and File->Properties will open the properties window.  Select Android and check a version of the ADK to compile against.  


<img width="784" alt="adk_settings" src="https://cloud.githubusercontent.com/assets/4631148/16553036/5045c2d4-418b-11e6-9663-079f9504ad7d.png">
