### ISSUE TITLE
virtual keyboard input with out enter

### ISSUE THREAD

**Issue by SanghwaHong** [ketai/ketai#20]
Hi, I really appreciate your effort on this library.

One thing I hope to know is about virtual keyboard of the Ketai library.
It works great but it is only activated when I press 'space bar' or 'enter'.
is there any possivility that I can use the keyboard input without 'enter' or 'space bar'?

At now, the println(key) is only show the 'key' when after I pressed 'enter' or 'space bar'.
I'm working on small app project which needs input text field but for few weeks of time, I stucked in this issue.

Since Apwidgets doesn't work on after Processing version 3, Ketai seems like only hope on my project.

**Comment by wolfm2** [comment]
Hi SanghwaHong,
 I'm having difficulties trying to understand the issue.  If you are still having a problem, let me know and please describe in detail what you are doing, how you expected the android device to respond and what it did differently.

Best,
Michael
