### ISSUE TITLE
Bluetooth Serial connection

### ISSUE THREAD

**Issue by dattasaurabh82** [ketai/ketai#24]
It would be great to have an example showing Arduino to bluetooth Serial connection.. I ouldn't wrap my head around for how o do it.. 

It's bit of an urgent. If anyone can help

**Comment by IngenieroElectronico** [comment]
Look 

https://www.youtube.com/channel/UCyWRJgfJMu3fiW4xO0FmB1w/videos?view=0&shelf_id=0&sort=dd

**Comment by ketai** [comment]
You can also refer to this post: http://prof-takaya.blogspot.com/2013/02/connecting-android-and-arduino-by.html
