### ISSUE TITLE
All Examples Stopped Working the First Time

### ISSUE THREAD

**Issue by lunchboxav** [ketai/ketai#27]
Hi,

Every time I build the Ketai examples and debug on device, it always crashes. It displays the "unfortunately xxx has stopped". However, I started with a simple program which just makes circles and it worked. Is there anything specific I had to do?

I'm using OnePlus One running Lollipop

**Comment by IngenieroElectronico** [comment]
Look in this channel good information of APDE, Ketai and Arduino:

https://www.youtube.com/channel/UCyWRJgfJMu3fiW4xO0FmB1w/videos?sort=dd&shelf_id=0&view=0

**Comment by ketai** [comment]
Updates to the new android mode and the upcoming final v13 build will resolve these issues.
