### ISSUE TITLE
No easy way to disconnect a single connected Bluetooth device.

### ISSUE THREAD

**Issue by mitchmindtree** [ketai/ketai#31]
After having a look through the KetaiBluetooth reference, it seems there is no easy way to disconnect an individual bluetooth device that doesn't involve `.stop()`ing and `.start()`ing the entire `KetaiBluetooth` instance. Please correct me if I'm wrong!

It seems there [might be a way](http://stackoverflow.com/questions/3031796/disconnect-a-bluetooth-socket-in-android) to do so via the internal `BluetoothAdaptor`. Will post back if I come up with a nice solution.

**Comment by ketai** [comment]
Added function to close connection.  disconnectDevice(String dev) function will attempt to resolve the name or HW address based on existing connections.
