### ISSUE TITLE
Camera example not working with Android 6

### ISSUE THREAD

**Issue by FlorentDeloison** [ketai/ketai#34]
I just tested the CameraGettingStarted example with Processing 3.1.1 + android Mode 252 on a Nexus 6P running Android 6, and the app is crashing at start.

**Comment by Gymnastictoast** [comment]
having the same problem with android 7

**Comment by Pablofero** [comment]
same, not working here with android 7.1.1

**Comment by ketai** [comment]
updated for latest androidMode
