### ISSUE TITLE
Not working on Android Mode 4

### ISSUE THREAD

**Issue by JuanIrache** [ketai/ketai#38]
Hi,

Processing's Android mode changed some changes in the way activities should be accessed, and that makes Ketai unusable.

I experienice this crash:

> 01-22 22:10:33.978 30783-30814/processing.test.sketch_170122a E/AndroidRuntime: FATAL EXCEPTION: Animation Thread Process: processing.test.sketch_170122a, PID: 30783 java.lang.NoSuchMethodError: No virtual method getActivity()Landroid/app/Activity; in class Lprocessing/core/PApplet; or its super classes (declaration of 'processing.core.PApplet' appears in /data/app/processing.test.sketch_170122a-2/base.apk) at ketai.camera.KetaiCamera.(KetaiCamera.java:130) at processing.test.sketch_170122a.sketch_170122a.setup(sketch_170122a.java:29) at processing.core.PApplet.handleDraw(Unknown Source) at processing.core.PSurfaceNone.callDraw(Unknown Source) at processing.core.PSurfaceNone$AnimationThread.run(Unknown Source) 01-22 22:10:33.978 30783-30814/processing.test.sketch_170122a E/AndroidRuntime: FATAL EXCEPTION: Animation Thread Process: processing.test.sketch_170122a, PID: 30783 java.lang.NoSuchMethodError: No virtual method getActivity()Landroid/app/Activity; in class Lprocessing/core/PApplet; or its super classes (declaration of 'processing.core.PApplet' appears in /data/app/processing.test.sketch_170122a-2/base.apk) at ketai.camera.KetaiCamera.(KetaiCamera.java:130) at processing.test.sketch_170122a.sketch_170122a.setup(sketch_170122a.java:29) at processing.core.PApplet.handleDraw(Unknown Source) at processing.core.PSurfaceNone.callDraw(Unknown Source) at processing.core.PSurfaceNone$AnimationThread.run(Unknown Source)

With this code

`import ketai.camera.*;
 
 KetaiCamera cam;
 
 void setup() {
     //fullScreen();
      orientation(LANDSCAPE);
     //imageMode(CENTER);
     cam = new KetaiCamera(this, 950, 540, 24);
     //background(0);
 }
 
 void onCameraPreviewEvent(){
   //cam.read();
 }
 
 void draw() {
 
 }`

You can find more info here:

https://forum.processing.org/two/discussion/18125/android-mode-4-support-to-keitai-camera-or-other-ways-to-access-camera

Thanks.

**Comment by ketai** [comment]
updated camera code is compatible with new android mode.  Camera example updated.
