### ISSUE TITLE
vibrate

### ISSUE THREAD

**Issue by niradler** [ketai/ketai#4]
while trying the to rub the UI example when i choose vibrate the app crash

**Comment by ketai** [comment]
What was your device, android version number?  Was there any out put in processing regarding the crash?  Was an exception thrown?

**Comment by niradler** [comment]
Phone: oneplus
Ver: 5.0.2
didn't notice any output, and i didn't get exception the app just close.
Hope its help sorry for not supplying this information before :)

**Comment by IngenieroElectronico** [comment]
Look sketch permision for vibrate

**Comment by wolfm2** [comment]
Closing this issue assuming it was a permissions issue.
