### ISSUE TITLE
Linux installer fails 

### ISSUE THREAD

**Issue by gratefulfrog** [ketai/ketai#43]
I've recently had some trouble installing Ketai Library v12 in Processing 3.3 on Xubuntu 16.04.

I use the Processing installer and the files download and deploy to the sketchbook/libraries directory.

The problem is that the top level directory is called `Ketai` with an uppercase `K` but further down in the hierarchy the jar file is called `ketai.jar` with a lowercase `k`.

The result is that the include directives fail, and Ketai never appears to be installed.

There is an open[ Processing Issue #4507](https://github.com/processing/processing/issues/4507) that refers. 

I only found the solution as a result of the issue I raised on the processing repo. [#4926](https://github.com/processing/processing/issues/4926).

Fixing this should take just a few seconds but how much better will it make all the user's lives!

Cheers,
Bob

**Comment by ketai** [comment]
Fixed in v14 and tested on Kali and Ubuntu
