### ISSUE TITLE
Audio recording file using the microphone

### ISSUE THREAD

**Issue by ThomasLengeling** [ketai/ketai#44]
Hello I am trying to build an app that saves the microphone input data to a sound file(mp3 or wav), Any chance that the library can accomplish this, or any recommendation. Thank you for your help
Thomas

**Comment by wolfm2** [comment]
Hi Thomas,
Although ketai does not handle encoding, it looks like there are three potential audio library possibilities: LibPD, Beads and Minim.  Minim's potential reliance on external non-java (en/de)coding libraries is causing issues for people using android mode.**   LibPD seems to be the only library for which I could find documented success***.  Luckily development still seems active.

From the link:

simply to pass buffers to Android's preferred Java objects:
android.media.AudioRecord
android.media.AudioTrack

-- for input and output, respectively.
You can check out Pd's code here:
https://github.com/libpd/libpd

** https://forum.processing.org/one/topic/get-fatal-exception-when-trying-to-run-a-sketch-with-minim.html
*** forum.processing.org/one/topic/sound-libraries.html

Best,
Michael
