### ISSUE TITLE
permissions body sensor

### ISSUE THREAD

**Issue by KIMDONG9** [ketai/ketai#46]
hi
now i;m trying to make heart-rate monitor with ketai sensors, but i thought i need to adding permission
body sensor. i can't find that in processing so do i add with  android manifest.xml manually?
or have another solution?

thanks for read stupid question bisous

**Comment by wolfm2** [comment]
Hi KIMDONG9,
I don't own a device that is capable of this, but from sources online it looks like you want the permission "BODY_SENSORS".   After updating to the latest Processing/Android SDK/Ketai it is listed for me in the permission selection drop-down menu.

Best,
Michael
