### ISSUE TITLE
WiFiDirect_remoteCursor problem

### ISSUE THREAD

**Issue by sesmusician** [ketai/ketai#52]
Hi i  am trying to make the example work, but OSC does not connect, sketch was working on version 3.0 of the processing android  mode, but since update it doesnt.

**Comment by wolfm2** [comment]
HI Sesmusician,
I'm happy to help.  A common problem here is that people forget to modify the sketch for their specific IP addresses.  Check out the walkthrough of these sketches here:
   https://www.mobileprocessing.org/networking.html

If none of these work for you, write back and let me know: 
Which sketch you are using.  
What problem you are experiencing.
What errors (if any) do you get during compiling or running.

Please copy and paste the full text of the error and the type of device (make and model) you were trying to run this on.

Best,
Michael
