### ISSUE TITLE
Face detection technique

### ISSUE THREAD

**Issue by nattykun** [ketai/ketai#56]
what type of face detection technology (eg. haar cascade, eigenfaces, etc) is being used for ketai face detection?

**Comment by wolfm2** [comment]
From the source file: 
KetaiFaceDetector wraps the android face detection api. The android face finding relies on eye detection and has limited accuracy but provides basic face detection without any external dependencies.

I looked around and couldn't find any articles that were explicit about what algorithms Google use but as a general overview, check out "3. Understanding Landmarks"  at  https://code.tutsplus.com/tutorials/an-introduction-to-face-detection-on-android--cms-25212
Also Google's API page:
https://developers.google.com/android/reference/com/google/android/gms/vision/face/FaceDetector

Best,
Michael
