### ISSUE TITLE
"Error during download and install of Android Mode"

### ISSUE THREAD

**Issue by JulioRadesca** [ketai/ketai#6]
I have followed the installation instructions of the Processing-Android Wiki, but when I try to add the Android Mode, I get this error message: "Error during download and install of Android Mode"
It seems like the download does not complete / does not open completely / or won't run. I am not sure. See image below. Thanks for the help.
![screen shot 2015-06-23 at 5 34 06 pm](https://cloud.githubusercontent.com/assets/13024163/8318046/9af81974-19cf-11e5-8bd4-f5b627feda33.png)

**Comment by JulioHH** [comment]
I got it working with an earlier version on processing (3.0.5).
