### ISSUE TITLE
add a release to fix Processing PDE broken download

### ISSUE THREAD

**Issue by jeremydouglass** [ketai/ketai#79]
Currently ketai is not listed in Processing Contributions Manager.

This is because these files listed in sources.conf:

http://ketailibrary.org/ketai.txt
http://ketailibrary.org/ketai.zip

...are no longer available since ketailibrary.org was decommissioned.

You can fix this very quickly in either of two ways:

1. add the ketai.txt and ketai.zip files to a path on ketai.org, and let us know what path.
2. upload the ketai.txt and ketai.zip files as attachments to a release on the Releases tab of this github repo! Then they can be linked from PDE and made automatically available to people who use Processing again.

with best regards,
Jeremy

processing/processing-website#387 (comment)

**Comment by ketai** [comment]
Hi Jeremy,

Thanks for catching this. We are on it (adding a release to Github). 
We‘ll fix the txt and zip on ketai.org as well.

Best,
Daniel

**Comment by jeremydouglass** [comment]
Thank you so much, Daniel!

Any release that you make will automatically receive a dynamic tag "latest" through github -- don't tag "latest" manually, just a normal tag like "v1.2". The latest release will then have a direct url to each attachment, like this:

https://github.com/ketai/ketai/releases/download/latest/ketai.txt
https://github.com/ketai/ketai/releases/download/latest/ketai.zip

Just post which your preferred urls are for Contributions Manager: GitHub, or 

http://ketai.org/ketai.txt
http://ketai.org/ketai.zip

**Comment by ketai** [comment]
Hi Jeremy,

We've updated to use

  http://ketai.org/ketai.txt
  http://ketai.org/ketai.zip

Thank you,

/jesus

**Comment by jeremydouglass** [comment]
@prisonerjohn -- could you update Contributions Manager with these new ketai urls please?

**Comment by prisonerjohn** [comment]
Just updated it, thanks!
